language: ruby
before_script:
  - gem update --system $RUBYGEMS_VERSION
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ruby-head
env:
  - RUBYGEMS_VERSION=1.8.29
  - RUBYGEMS_VERSION=2.0.14
  - RUBYGEMS_VERSION=2.2.2
  - RUBYGEMS_VERSION=2.4.1
matrix:
  exclude:
    - rvm: 2.0.0
      env: RUBYGEMS_VERSION=1.8.25
